import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { redirect } from 'next/navigation'

import { Header } from '@/components/header'
import { useValidateToken } from '@/hooks/useValidadeToken'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Panel - Trend Monitor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const isAuth = useValidateToken()

  if (!isAuth) redirect('/sign-in')

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
